exports.def = [
  "Command is wrong bro😒",
  "Koi sense hai is command ki?😆",
  "Nikal yaha se, pareshan mat kar😒",
  "Admin isko nikalo group se😒",
  "Galat commands deke pareshan kar diye ho😒",
  "😭😭😭",
  "Aisa koi command hai hi nahi🤨",
  "Insaan chutiye ho rahe aur BOT smart🤣",
  "😣😣",
  "😂🤣",
  "😏😒",
  "Bhai iska koi jawab nahi hai mere paas",
  "Aisa kucch immediate reply soche nahi hai",
  "bhai please maaf krde.. mere se naa hoga",
  "#menu dekh le bhai",
  "ab nahi de raha main reply😒",
  "spam karo saaalo.. fir bolna reply kyu nhi karta main😒😒",
  "ye kaisa command hai bhai?",
  "tere se zyada dimag toh mere paas hai😆😆",
];

exports.stickerreply = [
  "ye le tera sticker",
  "haa lo ban gyaa..",
  "here you go..",
  "I made sticker for you",
  "what else can i do for you?",
  "atleast thank me!",
  "thankyou bol saalee",
  "main tere liye sticker banaya..",
  "thank gaya hu banate banate😢",
  "ho gyaaaa😉",
  "dekh lo sahi se bana haina",
  "ye le.. bana daala",
  "your sticker is ready!",
  "try #stickertoimg for reverse",
  "ye le khush?😒",
  "Happy??😒",
  "Done Brother!",
  "Done Sister!",
  "this is your last sticker😒",
];

